/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.liavontsibrechka.api;

import net.liavontsibrechka.model.Credentials;
import net.liavontsibrechka.model.JwtToken;
import net.liavontsibrechka.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationControllerApi
 */
@Ignore
public class AuthenticationControllerApiTest {

    private final AuthenticationControllerApi api = new AuthenticationControllerApi();

    
    /**
     * login
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginUsingPOSTTest() {
        Credentials credentials = null;
        api.loginUsingPOST(credentials);

        // TODO: test validations
    }
    
    /**
     * refreshToken
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void refreshTokenUsingGETTest() {
        JwtToken response = api.refreshTokenUsingGET();

        // TODO: test validations
    }
    
    /**
     * registerUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerUserUsingPOSTTest() {
        User user = null;
        api.registerUserUsingPOST(user);

        // TODO: test validations
    }
    
}
