/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.liavontsibrechka.api;

import net.liavontsibrechka.model.Category;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CategoryControllerApi
 */
@Ignore
public class CategoryControllerApiTest {

    private final CategoryControllerApi api = new CategoryControllerApi();

    
    /**
     * addCategory
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addCategoryUsingPOSTTest() {
        Category category = null;
        api.addCategoryUsingPOST(category);

        // TODO: test validations
    }
    
    /**
     * removeCategory
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeCategoryUsingDELETETest() {
        Long id = null;
        api.removeCategoryUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * saveCategory
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveCategoryUsingPUTTest() {
        Long id = null;
        Category category = null;
        api.saveCategoryUsingPUT(id, category);

        // TODO: test validations
    }
    
    /**
     * showCategories
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showCategoriesUsingGETTest() {
        List<Category> response = api.showCategoriesUsingGET();

        // TODO: test validations
    }
    
}
