/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.liavontsibrechka.api;

import net.liavontsibrechka.model.Document;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocumentControllerApi
 */
@Ignore
public class DocumentControllerApiTest {

    private final DocumentControllerApi api = new DocumentControllerApi();

    
    /**
     * getFile
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFileUsingGETTest() {
        Long id = null;
        api.getFileUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * removeDocument
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeDocumentUsingDELETETest() {
        Long id = null;
        api.removeDocumentUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * saveNewDocument
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveNewDocumentUsingPOSTTest() {
        String properties = null;
        File file = null;
        api.saveNewDocumentUsingPOST(properties, file);

        // TODO: test validations
    }
    
    /**
     * showDocumentById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showDocumentByIdUsingGETTest() {
        Long id = null;
        Document response = api.showDocumentByIdUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * showDocumentList
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showDocumentListUsingGETTest() {
        String postedBy = null;
        String category = null;
        String documentType = null;
        String sortBy = null;
        Boolean sortAsc = null;
        Integer skip = null;
        Integer limit = null;
        List<Document> response = api.showDocumentListUsingGET(postedBy, category, documentType, sortBy, sortAsc, skip, limit);

        // TODO: test validations
    }
    
    /**
     * updateDocument
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDocumentUsingPUTTest() {
        String properties = null;
        String id = null;
        File file = null;
        api.updateDocumentUsingPUT(properties, id, file);

        // TODO: test validations
    }
    
}
