/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.liavontsibrechka.api;

import net.liavontsibrechka.model.DocumentType;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocumentTypeControllerApi
 */
@Ignore
public class DocumentTypeControllerApiTest {

    private final DocumentTypeControllerApi api = new DocumentTypeControllerApi();

    
    /**
     * addDocumentType
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addDocumentTypeUsingPOSTTest() {
        DocumentType documentType = null;
        api.addDocumentTypeUsingPOST(documentType);

        // TODO: test validations
    }
    
    /**
     * removeDocumentType
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeDocumentTypeUsingDELETETest() {
        Long id = null;
        api.removeDocumentTypeUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * saveDocumentType
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveDocumentTypeUsingPUTTest() {
        Long id = null;
        DocumentType documentType = null;
        api.saveDocumentTypeUsingPUT(id, documentType);

        // TODO: test validations
    }
    
    /**
     * showDocumentTypes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showDocumentTypesUsingGETTest() {
        List<DocumentType> response = api.showDocumentTypesUsingGET();

        // TODO: test validations
    }
    
}
