/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.liavontsibrechka.api;

import net.liavontsibrechka.model.Tag;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagControllerApi
 */
@Ignore
public class TagControllerApiTest {

    private final TagControllerApi api = new TagControllerApi();

    
    /**
     * addTag
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTagUsingPOSTTest() {
        Tag tag = null;
        api.addTagUsingPOST(tag);

        // TODO: test validations
    }
    
    /**
     * removeTag
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeTagUsingDELETETest() {
        Long id = null;
        api.removeTagUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * saveTag
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveTagUsingPUTTest() {
        Long id = null;
        Tag tag = null;
        api.saveTagUsingPUT(id, tag);

        // TODO: test validations
    }
    
    /**
     * saveTags
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveTagsUsingPUTTest() {
        List<Tag> tags = null;
        api.saveTagsUsingPUT(tags);

        // TODO: test validations
    }
    
    /**
     * showTags
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showTagsUsingGETTest() {
        String search = null;
        Integer skip = null;
        Integer limit = null;
        List<Tag> response = api.showTagsUsingGET(search, skip, limit);

        // TODO: test validations
    }
    
}
